'use client';
import {useEffect,useState} from 'react';
import ThreatGlobe from './ThreatGlobe';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8080';
export default function Page(){
 const [domain,setDomain]=useState('c2.bad-demo.example'),[result,setResult]=useState(),[events,setEvents]=useState([]),[incidents,setIncidents]=useState([]),[feeds,setFeeds]=useState([]),[monitoring,setMonitoring]=useState(),[error,setError]=useState('');
 const refresh=async()=>{try{setEvents(await(await fetch(API+'/v1/events')).json());setIncidents(await(await fetch(API+'/v1/incidents')).json());const health=await(await fetch(API+'/v1/feed-health')).json();setFeeds(health.feeds||[]);setMonitoring(await(await fetch(API+'/v1/model-monitoring')).json())}catch{setError('API unavailable: start the Docker Compose stack.')}};
 useEffect(()=>{refresh();const timer=setInterval(refresh,4000);return()=>clearInterval(timer)},[]);
 const investigate=async(e)=>{e.preventDefault();setError('');try{const response=await fetch(API+'/v1/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,client_ip:'172.28.0.99',source:'dashboard'})});setResult(await response.json());refresh()}catch{setError('Query failed: gateway unavailable.')}};
 const upload=async(e)=>{const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.append('file',file);const endpoint=file.name.endsWith('.pcap')?'/v1/passive/pcap':'/v1/passive/zeek';try{const data=await(await fetch(API+endpoint,{method:'POST',body:form})).json();setResult({verdict:'PASSIVE ANALYSIS',domain:file.name,domain_risk:0,confidence:'OFFLINE',reasons:[`Extracted ${data.extracted_queries?.length||0} DNS queries`,data.note||data.error||'']})}catch{setError('Upload failed.')}};
 const label=async(kind)=>{if(!result?.event_id)return;await fetch(`${API}/v1/events/${result.event_id}/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:kind})});};
 return <main><header><div><small>DNS SHIELD / SIH260003</small><h1>Threat Operations Center</h1></div><span className="status">● DETECTION PLANE ONLINE</span></header>
 <section className="query"><form onSubmit={investigate}><label>Investigate a DNS query</label><div><input value={domain} onChange={e=>setDomain(e.target.value)}/><button>Run pipeline</button></div></form>{error&&<p className="warn">{error}</p>}</section>
 <div className="grid"><section className="card wide"><h2>Live query stream</h2><table><thead><tr><th>Time</th><th>Domain</th><th>Verdict</th><th>Risk</th><th>Device</th></tr></thead><tbody>{events.map((e,i)=><tr key={e.event_id||i}><td>{e.timestamp}</td><td>{e.domain}</td><td className={e.verdict}>{e.verdict}</td><td>{e.domain_risk}</td><td>{e.client_ip}</td></tr>)}</tbody></table></section>
 <section className="card"><h2>XAI decision panel</h2>{result?<><p className={result.verdict}>{result.verdict} · score {result.domain_risk}</p><p>Confidence: {result.confidence} · {result.latency_ms} ms</p><ul>{result.reasons?.map((x,i)=><li key={i}>{x}</li>)}</ul><small>ML band: {result.ml?.uncertainty_band||'offline'} · cache {result.cache||'n/a'}</small><div className="buttons"><button onClick={()=>label('False Positive')}>False Positive</button><button onClick={()=>label('Confirmed Threat')}>Confirmed Threat</button><button onClick={()=>label('Needs Investigation')}>Needs Investigation</button></div></>:<p>Run a query to see both allow and block explanations.</p>}</section>
 <section className="card"><h2>Incident timeline</h2>{incidents.length?incidents.map(x=><article key={x.id}><b>{x.severity?.toUpperCase()} · {x.device}</b><p>{x.summary}</p></article>):<p>No correlated incidents yet.</p>}</section>
 <section className="card"><h2>Passive analysis</h2><input type="file" accept=".pcap,.log,.tsv" onChange={upload}/><p>Upload a PCAP or Zeek TSV to extract historical DNS queries for pipeline replay.</p></section>
 <section className="card"><h2>Threat feed health</h2>{feeds.map(x=><p key={x.name}>{x.name}: <b>{x.status}</b></p>)}</section>
 <section className="card"><h2>Live 3D threat globe</h2><ThreatGlobe events={events}/><small>Red arcs are blocked queries. GeoLite2 coordinates are used when present; demo fallback positions are deterministic.</small></section>
 <section className="card"><h2>Response controls</h2><p>Lab-only quarantine and sinkholing are automatic at critical thresholds.</p><code>DELETE /v1/quarantine/:ip</code></section>
 <section className="card"><h2>Model monitoring</h2><p>Model: {monitoring?.model_version||'loading'}</p><p>Metrics: {monitoring?.metrics_status||'loading'}</p><p>Drift: {monitoring?.feature_drift?.indicator||monitoring?.feature_drift?.status||'loading'}</p><p>Latency appears on each inference result.</p></section></div></main>}
