'use client';
import {useEffect,useState} from 'react';
import ThreatGlobe from './ThreatGlobe';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8080';

function scoreRow(stats, verdict){return stats?.by_verdict?.find(row=>row.verdict===verdict)?.count||0}

export default function Page(){
 const [domain,setDomain]=useState('c2.bad-demo.example'),[result,setResult]=useState(),[events,setEvents]=useState([]),[incidents,setIncidents]=useState([]),[feeds,setFeeds]=useState([]),[monitoring,setMonitoring]=useState(),[stats,setStats]=useState(),[trends,setTrends]=useState({points:[]}),[quarantine,setQuarantine]=useState({rules:{}}),[profile,setProfile]=useState(),[error,setError]=useState('');
 const refresh=async()=>{try{const [eventRows,incidentRows,health,model,summary,trendRows,response]=await Promise.all([fetch(API+'/v1/events').then(r=>r.json()),fetch(API+'/v1/incidents').then(r=>r.json()),fetch(API+'/v1/feed-health').then(r=>r.json()),fetch(API+'/v1/model-monitoring').then(r=>r.json()),fetch(API+'/v1/stats').then(r=>r.json()),fetch(API+'/v1/trends').then(r=>r.json()),fetch(API+'/v1/quarantine').then(r=>r.json())]);setEvents(eventRows);setIncidents(incidentRows);setFeeds(health.feeds||[]);setMonitoring(model);setStats(summary);setTrends(trendRows);setQuarantine(response)}catch{setError('One or more API services are unavailable. Check the Compose stack and service health.')}};
 useEffect(()=>{refresh();const timer=setInterval(refresh,4000);return()=>clearInterval(timer)},[]);
 const investigate=async(e)=>{e.preventDefault();setError('');try{const response=await fetch(API+'/v1/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,client_ip:'172.28.0.99',source:'dashboard'})});const body=await response.json();if(!response.ok)throw new Error(body.detail||'query failed');setResult(body);refresh()}catch(error){setError(`Query failed: ${error.message}`)}};
 const inspect=async(event)=>{setResult(event);try{const device=await fetch(`${API}/v1/devices/${event.client_ip}`).then(r=>r.json());const domainData=await fetch(`${API}/v1/domains/${event.domain}`).then(r=>r.json());setProfile({device,domain:domainData})}catch{setProfile(undefined)}};
 const upload=async(e)=>{const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.append('file',file);const endpoint=file.name.endsWith('.pcap')?'/v1/passive/pcap':'/v1/passive/zeek';try{const data=await(await fetch(API+endpoint,{method:'POST',body:form})).json();setResult({verdict:'PASSIVE ANALYSIS',domain:file.name,domain_risk:0,confidence:'OFFLINE',reasons:[`Extracted and replayed ${data.queries_extracted||0} DNS queries`,data.parser_note||data.parser_error||'']});refresh()}catch{setError('Passive upload failed.')}};
 const label=async(kind)=>{if(!result?.event_id)return;await fetch(`${API}/v1/events/${result.event_id}/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:kind})});};
 const release=async(ip)=>{await fetch(`${API}/v1/quarantine/${ip}`,{method:'DELETE'});refresh()};
 return <main><header><div><small>DNS SHIELD / SIH260003</small><h1>Threat Operations Center</h1></div><span className="status">● DETECTION PLANE ONLINE</span></header>
 <section className="metrics"><div><small>Allowed / 24h</small><b>{scoreRow(stats,'ALLOW')}</b></div><div><small>Flagged / 24h</small><b className="FLAG">{scoreRow(stats,'FLAG')}</b></div><div><small>Blocked / 24h</small><b className="BLOCK">{scoreRow(stats,'BLOCK')}</b></div><div><small>Open incidents</small><b>{incidents.length}</b></div></section>
 <section className="query"><form onSubmit={investigate}><label>Investigate a DNS query</label><div><input value={domain} onChange={e=>setDomain(e.target.value)}/><button>Run pipeline</button></div></form>{error&&<p className="warn">{error}</p>}</section>
 <div className="grid"><section className="card wide"><h2>Live query stream</h2><table><thead><tr><th>Time</th><th>Domain</th><th>Verdict</th><th>Risk</th><th>Device</th></tr></thead><tbody>{events.map((event,index)=><tr key={event.event_id||index} onClick={()=>inspect(event)} className="clickable"><td>{event.timestamp}</td><td>{event.domain}</td><td className={event.verdict}>{event.verdict}</td><td>{event.domain_risk}</td><td>{event.client_ip}</td></tr>)}</tbody></table><small>Click an event to inspect its evidence and reputation context.</small></section>
 <section className="card"><h2>XAI decision panel</h2>{result?<><p className={result.verdict}>{result.verdict} · score {result.domain_risk}</p><p>Confidence: {result.confidence} · {result.latency_ms??'stored'} ms</p><ol className="pipeline">{result.pipeline?.map((item,index)=><li key={index}><b>{item.stage}</b> — {item.status}; +{item.contribution||0}<small>{item.reason}</small></li>)}</ol>{!result.pipeline&&<ul>{result.reasons?.map((reason,index)=><li key={index}>{reason}</li>)}</ul>}<div className="buttons"><button onClick={()=>label('False Positive')}>False Positive</button><button onClick={()=>label('Confirmed Threat')}>Confirmed Threat</button><button onClick={()=>label('Needs Investigation')}>Needs Investigation</button></div></>:<p>Run a query or select an event to view evidence.</p>}</section>
 <section className="card"><h2>Reputation context</h2>{profile?<><p>Device risk: <b>{profile.device?.risk}</b></p><p>Domain devices: <b>{profile.domain?.device_count}</b></p><p>Parent: {profile.domain?.parent_domain}</p><small>{profile.domain?.parent_poisoning_analysis?.reason}</small></>:<p>Select a stored event to load device and domain history.</p>}</section>
 <section className="card"><h2>Incident timeline</h2>{incidents.length?incidents.map(item=><article key={item.id}><b>{item.severity?.toUpperCase()} · {item.device}</b><p>{item.summary}</p><small>{item.timeline?.length||0} timeline entries</small></article>):<p>No correlated incidents yet.</p>}</section>
 <section className="card"><h2>24-hour security trend</h2>{trends.points?.length?<div className="trend">{trends.points.map((point,index)=><div key={point.hour||index} title={`${point.hour}: ${point.query_count} queries, ${point.blocked_count} blocked`}><i style={{height:`${Math.max(5,Math.min(100,Number(point.avg_domain_risk)||0))}%`}}/><small>{point.blocked_count}B / {point.flagged_count}F</small></div>)}</div>:<p>No time-series events yet.</p>}<small>Bar height is average domain risk; labels show blocked/flagged counts per hour.</small></section>
 <section className="card"><h2>Passive analysis</h2><input type="file" accept=".pcap,.pcapng,.log,.tsv" onChange={upload}/><p>Upload PCAP, PCAPNG, or Zeek TSV. Extracted DNS queries replay through the same pipeline.</p></section>
 <section className="card"><h2>Threat feed health</h2>{feeds.map(feed=><p key={feed.name}>{feed.name}: <b>{feed.status}</b><small> {feed.indicators_added||0} added</small></p>)}</section>
 <section className="card"><h2>Live 3D threat globe</h2><ThreatGlobe events={events}/><small>Red arcs are blocked queries; GeoLite2 coordinates are used when available.</small></section>
 <section className="card"><h2>Lab response controls</h2>{Object.keys(quarantine.rules||{}).length?Object.entries(quarantine.rules).map(([ip,rule])=><p key={ip}>{ip} <button onClick={()=>release(ip)}>Release</button><small> {rule.reason}</small></p>):<p>No virtual-lab devices quarantined.</p>}<small>No host firewall changes are made.</small></section>
 <section className="card"><h2>Model monitoring</h2><p>Model: {monitoring?.model_version||'loading'}</p><p>Metrics: {monitoring?.metrics_status||'loading'}</p><p>Drift: {monitoring?.feature_drift?.indicator||monitoring?.feature_drift?.status||'loading'}</p><p>Latency is displayed on each live decision.</p></section></div></main>}
