"""DNS Shield — Live Attack Simulation & Evidence Demonstration.

Runs 5 realistic attack scenarios against the local DNS Shield gateway:
1. Benign Traffic (isro.gov.in, google.com)
2. DGA Malware Infiltration (xq9m2kz7v4na.com, lq3zp89vbcx.net, ad7qxm91bz.io)
3. Typosquatting / Brand Impersonation (gooogle.com, isro-gov.in)
4. C2 Command & Control Beaconing (c2.bad-demo.example)
5. Covert DNS Tunneling Exfiltration (high-entropy 60-char label)
"""

import json
import os
import sys
import time
import requests

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

GATEWAY_URL = os.getenv("GATEWAY_URL", "http://localhost:8081/v1/query")

# ANSI color codes
RESET = "\033[0m"
BOLD = "\033[1m"
GREEN = "\033[32m"
RED = "\033[31m"
YELLOW = "\033[33m"
CYAN = "\033[36m"
MAGENTA = "\033[35m"

SCENARIOS = [
    {
        "category": "BENIGN TRAFFIC (ALLOWLIST & NORMAL)",
        "desc": "Legitimate domains; should resolve with ALLOW and 0% risk.",
        "domains": [
            ("isro.gov.in", "192.168.1.10", "dashboard"),
            ("google.com", "192.168.1.11", "dashboard"),
        ],
    },
    {
        "category": "DGA MALWARE DOMAINS (AI / LEXICAL CLASSIFIER)",
        "desc": "Algorithmic DGA domains generated by Conficker/Matsnu/Kraken. Evaluated by dga-v2 (99.7% acc).",
        "domains": [
            ("lq3zp89vbcx.net", "192.168.1.105", "lab-simulation:dga"),
            ("ad7qxm91bz.io", "192.168.1.105", "lab-simulation:dga"),
        ],
    },
    {
        "category": "TYPOSQUATTING & BRAND HOMOGLYPHS",
        "desc": "Deceptive brand impersonation targeting government and major platforms.",
        "domains": [
            ("gooogle.com", "192.168.1.200", "lab-simulation:typosquat"),
            ("isro-gov.in", "192.168.1.200", "lab-simulation:typosquat"),
        ],
    },
    {
        "category": "C2 COMMAND & CONTROL INFRASTRUCTURE",
        "desc": "Active threat intelligence match against known malicious C2 nodes.",
        "domains": [
            ("c2.bad-demo.example", "192.168.1.150", "lab-simulation:c2"),
        ],
    },
    {
        "category": "COVERT DNS TUNNELING / EXFILTRATION",
        "desc": "High-entropy base16/base64 encoded payload tunneling across Port 53.",
        "domains": [
            ("abcdef0123456789abcdef0123456789abcdef0123456789.exfil-demo.example", "192.168.1.199", "lab-simulation:tunnelling"),
        ],
    },
]

def print_header(title):
    print(f"\n{BOLD}{CYAN}{'=' * 75}{RESET}", flush=True)
    print(f"{BOLD}{CYAN}  {title}{RESET}", flush=True)
    print(f"{BOLD}{CYAN}{'=' * 75}{RESET}", flush=True)

def run_query(domain, client_ip, source):
    payload = {"domain": domain, "client_ip": client_ip, "source": source}
    try:
        t0 = time.perf_counter()
        resp = requests.post(GATEWAY_URL, json=payload, timeout=12)
        elapsed_ms = (time.perf_counter() - t0) * 1000
        
        if resp.status_code != 200:
            print(f"  {RED}[ERROR] Gateway returned HTTP {resp.status_code}: {resp.text}{RESET}", flush=True)
            return
            
        data = resp.json()
        verdict = data.get("verdict", "UNKNOWN")
        risk = data.get("domain_risk", 0)
        dev_risk = data.get("device_risk", 0)
        conf = data.get("confidence", "N/A")
        reasons = data.get("reasons", [])
        ml = data.get("ml")
        cache = data.get("cache", "miss")
        latency = data.get("latency_ms", round(elapsed_ms, 2))
        
        v_color = RED if verdict == "BLOCK" else (YELLOW if verdict == "FLAG" else GREEN)
        
        print(f"  {BOLD}Domain:{RESET} {domain:<45}", flush=True)
        print(f"    |-- Verdict:      {v_color}{BOLD}{verdict:<8}{RESET} (Confidence: {conf})", flush=True)
        print(f"    |-- Risk Scores:  Domain {risk}/100 | Device {dev_risk}/100", flush=True)
        print(f"    |-- Latency:      {latency} ms ({'Redis Cache' if cache == 'hit' else 'Full 7-Stage Pipeline'})", flush=True)
        
        if ml:
            prob = ml.get("dga_probability", 0.0)
            mode = ml.get("inference_mode", "local")
            ver = ml.get("model_version", "v2")
            print(f"    |-- ML Engine:    {ver} [{mode}] (DGA Prob: {prob*100:.1f}%)", flush=True)
            
        if reasons:
            reasons_str = "; ".join(reasons[:2])
            print(f"    \\-- Key Evidence: {reasons_str}", flush=True)
        print(flush=True)
        
    except Exception as e:
        print(f"  {RED}[FAILED] Query to {domain} failed: {e}{RESET}", flush=True)

def main():
    print(f"{BOLD}{MAGENTA}")
    print("  ____  _   _ ____    ____  _   _ ___ _____ _     ____  ")
    print(" |  _ \\| \\ | / ___|  / ___|| | | |_ _| ____| |   |  _ \\ ")
    print(" | | | |  \\| \\___ \\  \\___ \\| |_| || ||  _| | |   | | | |")
    print(" | |_| | |\\  |___) |  ___) |  _  || || |___| |___| |_| |")
    print(" |____/|_| \\_|____/  |____/|_| |_|___|_____|_____|____/ ")
    print(f"       Live Attack & Threat Detection Demo Suite{RESET}")
    print(f"       Gateway Target: {GATEWAY_URL}\n")
    
    for s in SCENARIOS:
        print_header(s["category"])
        print(f"{CYAN}Description: {s['desc']}{RESET}\n")
        for domain, ip, src in s["domains"]:
            run_query(domain, ip, src)
            time.sleep(0.3)

    print_header("DEMO SUMMARY & DASHBOARD LINKS")
    print(f"  {GREEN}[+] All simulation events logged to Analytics Store & Forensics DB{RESET}")
    print(f"  - SOC Live Dashboard:    {BOLD}http://localhost:3000/app/dashboard{RESET}")
    print(f"  - Forensics & Analytics: {BOLD}http://localhost:3000/app/analytics{RESET}")
    print(f"  - Kill-Chain Forecast:   {BOLD}http://localhost:3000/app/forecast{RESET}")
    print(f"  - Explainable AI (SHAP): {BOLD}http://localhost:3000/app/xai{RESET}")
    print(f"  - ML Model Card Specs:   {BOLD}http://localhost:3000/app/models{RESET}")
    print()

if __name__ == "__main__":
    main()
